config/routes.rb
Rails.application.routes.draw do
  resources :employer_infos
  resources :profile_infos
  get 'user_pages/profile'

  get 'user_pages/browse_jobs'

  get 'user_pages/employers'

  resources :skillsets
  resources :work_cultures
  resources :work_cultures
  resources :work_cultures
  resources :profiles
  get 'admin/adminpage1'

  get 'admin/adminpage'

  get 'admin/2'

  get 'welcome/dhome'

  get 'welcome/home'

  root 'welcome#dhome'

  get 'home' => 'welcome#dhome'

  get 'profile' => 'user_pages#profile'

  get 'browse_jobs' => 'user_pages#browse_jobs'

  get 'employers' => 'user_pages#employers'

end

app/models/employer_info.rb
class EmployerInfo < ActiveRecord::Base
end

app/controllers/employer_infos_controller.rb
class EmployerInfosController < ApplicationController
  before_action :set_employer_info, only: [:show, :edit, :update, :destroy]

  # GET /employer_infos
  # GET /employer_infos.json
  def index
    @employer_infos = EmployerInfo.all
  end

  # GET /employer_infos/1
  # GET /employer_infos/1.json
  def show
  end

  # GET /employer_infos/new
  def new
    @employer_info = EmployerInfo.new
  end

  # GET /employer_infos/1/edit
  def edit
  end

  # POST /employer_infos
  # POST /employer_infos.json
  def create
    @employer_info = EmployerInfo.new(employer_info_params)

    respond_to do |format|
      if @employer_info.save
        format.html { redirect_to @employer_info, notice: 'Employer info was successfully created.' }
        format.json { render :show, status: :created, location: @employer_info }
      else
        format.html { render :new }
        format.json { render json: @employer_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employer_infos/1
  # PATCH/PUT /employer_infos/1.json
  def update
    respond_to do |format|
      if @employer_info.update(employer_info_params)
        format.html { redirect_to @employer_info, notice: 'Employer info was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer_info }
      else
        format.html { render :edit }
        format.json { render json: @employer_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employer_infos/1
  # DELETE /employer_infos/1.json
  def destroy
    @employer_info.destroy
    respond_to do |format|
      format.html { redirect_to employer_infos_url, notice: 'Employer info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer_info
      @employer_info = EmployerInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_info_params
      params.require(:employer_info).permit(:client_id, :companyName, :city, :state)
    end
end

app/helpers/employer_infos_helper.rb
module EmployerInfosHelper
end

app/views/employer_infos/_form.html.erb
<%= form_for(@employer_info) do |f| %>
  <% if @employer_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer_info.errors.count, "error") %> prohibited this employer_info from being saved:</h2>

      <ul>
      <% @employer_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.select :client_id, [current_user.id]  %>
  </div>
  <div class="field">
    <%= f.label :companyName %><br>
    <%= f.text_field :companyName %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employer_infos/edit.html.erb
<h1>Editing Employer Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer_info %> |
<%= link_to 'Back', employer_infos_path %>

app/views/employer_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employer Infos</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Companyname</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employer_infos.each do |employer_info| %>
      <tr>
        <td><%= employer_info.client_id %></td>
        <td><%= employer_info.companyName %></td>
        <td><%= employer_info.city %></td>
        <td><%= employer_info.state %></td>
        <td><%= link_to 'Show', employer_info %></td>
        <td><%= link_to 'Edit', edit_employer_info_path(employer_info) %></td>
        <td><%= link_to 'Destroy', employer_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer info', new_employer_info_path %>

app/views/employer_infos/new.html.erb
<h1>New Employer Info</h1>

<%= render 'form' %>

<%= link_to 'Back', employer_infos_path %>

app/views/employer_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @employer_info.client_id %>
</p>

<p>
  <strong>Companyname:</strong>
  <%= @employer_info.companyName %>
</p>

<p>
  <strong>City:</strong>
  <%= @employer_info.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employer_info.state %>
</p>

<%= link_to 'Edit', edit_employer_info_path(@employer_info) %> |
<%= link_to 'Back', employer_infos_path %>