config/routes.rb
Rails.application.routes.draw do
  resources :employer_infos
  resources :profile_infos
  get 'user_pages/profile'

  get 'user_pages/browse_jobs'

  get 'user_pages/employers'

  resources :skillsets
  resources :work_cultures
  resources :work_cultures
  resources :work_cultures
  resources :profiles
  get 'admin/adminpage1'

  get 'admin/adminpage'

  get 'admin/2'

  get 'welcome/dhome'

  get 'welcome/home'

  root 'welcome#dhome'

  get 'home' => 'welcome#dhome'

  get 'profile' => 'user_pages#profile'

  get 'browse_jobs' => 'user_pages#browse_jobs'

  get 'employers' => 'user_pages#employers'

end

app/models/work_culture.rb
class WorkCulture < ActiveRecord::Base
  belongs_to :user
end

app/controllers/work_cultures_controller.rb
class WorkCulturesController < ApplicationController
  before_action :set_work_culture, only: [:show, :edit, :update, :destroy]

  # GET /work_cultures
  # GET /work_cultures.json
  def index
    @work_cultures = WorkCulture.all
  end

  # GET /work_cultures/1
  # GET /work_cultures/1.json
  def show
  end

  # GET /work_cultures/new
  def new
    @work_culture = WorkCulture.new
  end

  # GET /work_cultures/1/edit
  def edit
  end

  # POST /work_cultures
  # POST /work_cultures.json
  def create
    @work_culture = WorkCulture.new(work_culture_params)

    respond_to do |format|
      if @work_culture.save
        format.html { redirect_to @work_culture, notice: 'Work culture was successfully created.' }
        format.json { render :show, status: :created, location: @work_culture }
      else
        format.html { render :new }
        format.json { render json: @work_culture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_cultures/1
  # PATCH/PUT /work_cultures/1.json
  def update
    respond_to do |format|
      if @work_culture.update(work_culture_params)
        format.html { redirect_to @work_culture, notice: 'Work culture was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_culture }
      else
        format.html { render :edit }
        format.json { render json: @work_culture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_cultures/1
  # DELETE /work_cultures/1.json
  def destroy
    @work_culture.destroy
    respond_to do |format|
      format.html { redirect_to work_cultures_url, notice: 'Work culture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_culture
      @work_culture = WorkCulture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_culture_params
      params.require(:work_culture).permit(:client_id, :creative, :logical, :problem_solver, :listener, :oral_communicator, :written_communicator, :people_skills, :punctual, :accurate, :efficient, :multitasker, :planner, :researcher, :leader, :leader, :team_member)
    end
end

app/helpers/work_cultures_helper.rb
module WorkCulturesHelper
end

app/views/work_cultures/_form.html.erb
<%= form_for(@work_culture) do |f| %>
  <% if @work_culture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_culture.errors.count, "error") %> prohibited this work_culture from being saved:</h2>

      <ul>
      <% @work_culture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.select :client_id, [current_user.id] %>
  </div>
  <div class="field">
    <%= f.label :creative %><br>
    <%= f.number_field :creative %>
  </div>
  <div class="field">
    <%= f.label :logical %><br>
    <%= f.number_field :logical %>
  </div>
  <div class="field">
    <%= f.label :problem_solver %><br>
    <%= f.number_field :problem_solver %>
  </div>
  <div class="field">
    <%= f.label :listener %><br>
    <%= f.number_field :listener %>
  </div>
  <div class="field">
    <%= f.label :oral_communicator %><br>
    <%= f.number_field :oral_communicator %>
  </div>
  <div class="field">
    <%= f.label :written_communicator %><br>
    <%= f.number_field :written_communicator %>
  </div>
  <div class="field">
    <%= f.label :people_skills %><br>
    <%= f.number_field :people_skills %>
  </div>
  <div class="field">
    <%= f.label :punctual %><br>
    <%= f.number_field :punctual %>
  </div>
  <div class="field">
    <%= f.label :accurate %><br>
    <%= f.number_field :accurate %>
  </div>
  <div class="field">
    <%= f.label :efficient %><br>
    <%= f.number_field :efficient %>
  </div>
  <div class="field">
    <%= f.label :multitasker %><br>
    <%= f.number_field :multitasker %>
  </div>
  <div class="field">
    <%= f.label :planner %><br>
    <%= f.number_field :planner %>
  </div>
  <div class="field">
    <%= f.label :researcher %><br>
    <%= f.number_field :researcher %>
  </div>
  <div class="field">
    <%= f.label :leader %><br>
    <%= f.number_field :leader %>
  </div>
  <div class="field">
    <%= f.label :team_member %><br>
    <%= f.number_field :team_member %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_cultures/edit.html.erb
<h1>Editing Work Culture</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_culture %> |
<%= link_to 'Back', work_cultures_path %>

app/views/work_cultures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Work Cultures</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Creative</th>
      <th>Logical</th>
      <th>Problem solver</th>
      <th>Listener</th>
      <th>Oral communicator</th>
      <th>Written communicator</th>
      <th>People skills</th>
      <th>Punctual</th>
      <th>Accurate</th>
      <th>Efficient</th>
      <th>Multitasker</th>
      <th>Planner</th>
      <th>Researcher</th>
      <th>Leader</th>
      <th>Team member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_cultures.each do |work_culture| %>
      <tr>
        <td><%= work_culture.client_id %></td>
        <td><%= work_culture.creative %></td>
        <td><%= work_culture.logical %></td>
        <td><%= work_culture.problem_solver %></td>
        <td><%= work_culture.listener %></td>
        <td><%= work_culture.oral_communicator %></td>
        <td><%= work_culture.written_communicator %></td>
        <td><%= work_culture.people_skills %></td>
        <td><%= work_culture.punctual %></td>
        <td><%= work_culture.accurate %></td>
        <td><%= work_culture.efficient %></td>
        <td><%= work_culture.multitasker %></td>
        <td><%= work_culture.planner %></td>
        <td><%= work_culture.researcher %></td>
        <td><%= work_culture.leader %></td>
        <td><%= work_culture.team_member %></td>
        <td><%= link_to 'Show', work_culture %></td>
        <td><%= link_to 'Edit', edit_work_culture_path(work_culture) %></td>
        <td><%= link_to 'Destroy', work_culture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work culture', new_work_culture_path %>

app/views/work_cultures/new.html.erb
<h1>New Work Culture</h1>

<%= render 'form' %>

<%= link_to 'Back', work_cultures_path %>

app/views/work_cultures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @work_culture.client_id %>
</p>

<p>
  <strong>Creative:</strong>
  <%= @work_culture.creative %>
</p>

<p>
  <strong>Logical:</strong>
  <%= @work_culture.logical %>
</p>

<p>
  <strong>Problem solver:</strong>
  <%= @work_culture.problem_solver %>
</p>

<p>
  <strong>Listener:</strong>
  <%= @work_culture.listener %>
</p>

<p>
  <strong>Oral communicator:</strong>
  <%= @work_culture.oral_communicator %>
</p>

<p>
  <strong>Written communicator:</strong>
  <%= @work_culture.written_communicator %>
</p>

<p>
  <strong>People skills:</strong>
  <%= @work_culture.people_skills %>
</p>

<p>
  <strong>Punctual:</strong>
  <%= @work_culture.punctual %>
</p>

<p>
  <strong>Accurate:</strong>
  <%= @work_culture.accurate %>
</p>

<p>
  <strong>Efficient:</strong>
  <%= @work_culture.efficient %>
</p>

<p>
  <strong>Multitasker:</strong>
  <%= @work_culture.multitasker %>
</p>

<p>
  <strong>Planner:</strong>
  <%= @work_culture.planner %>
</p>

<p>
  <strong>Researcher:</strong>
  <%= @work_culture.researcher %>
</p>

<p>
  <strong>Leader:</strong>
  <%= @work_culture.leader %>
</p>

<p>
  <strong>Team member:</strong>
  <%= @work_culture.team_member %>
</p>

<%= link_to 'Edit', edit_work_culture_path(@work_culture) %> |
<%= link_to 'Back', work_cultures_path %>