config/routes.rb
Rails.application.routes.draw do
  resources :employer_infos
  resources :profile_infos
  get 'user_pages/profile'

  get 'user_pages/browse_jobs'

  get 'user_pages/employers'

  resources :skillsets
  resources :work_cultures
  resources :work_cultures
  resources :work_cultures
  resources :profiles
  get 'admin/adminpage1'

  get 'admin/adminpage'

  get 'admin/2'

  get 'welcome/dhome'

  get 'welcome/home'

  root 'welcome#dhome'

  get 'home' => 'welcome#dhome'

  get 'profile' => 'user_pages#profile'

  get 'browse_jobs' => 'user_pages#browse_jobs'

  get 'employers' => 'user_pages#employers'

end

app/models/profile_info.rb
class ProfileInfo < ActiveRecord::Base
end

app/controllers/profile_infos_controller.rb
class ProfileInfosController < ApplicationController
  before_action :set_profile_info, only: [:show, :edit, :update, :destroy]

  # GET /profile_infos
  # GET /profile_infos.json
  def index
    @profile_infos = ProfileInfo.all
  end

  # GET /profile_infos/1
  # GET /profile_infos/1.json
  def show
  end

  # GET /profile_infos/new
  def new
    @profile_info = ProfileInfo.new
  end

  # GET /profile_infos/1/edit
  def edit
  end

  # POST /profile_infos
  # POST /profile_infos.json
  def create
    @profile_info = ProfileInfo.new(profile_info_params)

    respond_to do |format|
      if @profile_info.save
        format.html { redirect_to @profile_info, notice: 'Profile info was successfully created.' }
        format.json { render :show, status: :created, location: @profile_info }
      else
        format.html { render :new }
        format.json { render json: @profile_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile_infos/1
  # PATCH/PUT /profile_infos/1.json
  def update
    respond_to do |format|
      if @profile_info.update(profile_info_params)
        format.html { redirect_to @profile_info, notice: 'Profile info was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile_info }
      else
        format.html { render :edit }
        format.json { render json: @profile_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_infos/1
  # DELETE /profile_infos/1.json
  def destroy
    @profile_info.destroy
    respond_to do |format|
      format.html { redirect_to profile_infos_url, notice: 'Profile info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile_info
      @profile_info = ProfileInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_info_params
      params.require(:profile_info).permit(:client_id, :fname, :lname, :city, :state)
    end
end

app/helpers/profile_infos_helper.rb
module ProfileInfosHelper
end

app/views/profile_infos/_form.html.erb
<%= form_for(@profile_info) do |f| %>
  <% if @profile_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile_info.errors.count, "error") %> prohibited this profile_info from being saved:</h2>

      <ul>
      <% @profile_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.select :client_id, [current_user.id] %>
  </div>
  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profile_infos/edit.html.erb
<h1>Editing Profile Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile_info %> |
<%= link_to 'Back', profile_infos_path %>

app/views/profile_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profile Infos</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profile_infos.each do |profile_info| %>
      <tr>
        <td><%= profile_info.client_id %></td>
        <td><%= profile_info.fname %></td>
        <td><%= profile_info.lname %></td>
        <td><%= profile_info.city %></td>
        <td><%= profile_info.state %></td>
        <td><%= link_to 'Show', profile_info %></td>
        <td><%= link_to 'Edit', edit_profile_info_path(profile_info) %></td>
        <td><%= link_to 'Destroy', profile_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile info', new_profile_info_path %>

app/views/profile_infos/new.html.erb
<h1>New Profile Info</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_infos_path %>

app/views/profile_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @profile_info.client_id %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @profile_info.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @profile_info.lname %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile_info.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile_info.state %>
</p>

<%= link_to 'Edit', edit_profile_info_path(@profile_info) %> |
<%= link_to 'Back', profile_infos_path %>